### ISSUE TITLE
[INCOMPATIBILITY] Very Many People (VMP): optimized entity tracking messing up with hook's collision

### ISSUE THREAD

**Issue by iSimilaXi** [squeeglii/grapplemod-restitched#1]
**Describe the bug**
When using grappling hook with VMP's optimized entity tracking settings (enabled by default), the grappling hook's collision is inaccurate. (Float in the air, near the wall that it was supposed to landing at.)

**Video / Screenshots**
![image](https://user-images.githubusercontent.com/93301357/219865036-7c21d383-1f29-4c0b-bfea-9a8e75a0d179.png)

**Version**
Include the versions for:
 - The Grapple Hook Mod v1.3
 - Fabric 0.14.14 + Fabric API 0.73.2
 - Minecraft 1.19.2
 - Very Many People 0.2.0+beta.7.28 (backport for 1.19.2)

**Steps To Reproduce**
1. While using VMP, right click to activate the grappling hook near a wall.
2. Check the grappling hook collision.

**Additional context**
- Changing use_optimized_entity_tracking to false in vmp.properties config fixed the problem.
- I believe this could possibly be the culprit: https://github.com/RelativityMC/VMP-fabric/blob/639c8330cde3000d0d7b7212ea2027f0b78b5af8/src/main/java/com/ishland/vmp/mixins/entitytracker/MixinEntityTrackerEntry.java

ps1. I also did a bug report on VMP's github page as well, just in case it can't be fixed on your side.
ps2. you should make a discord server btw

**Comment by squeeglii** [comment]
Reproduced it! - Investigating. Seems to have some server and client desync

**Comment by squeeglii** [comment]
> I believe this could possibly be the culprit: https://github.com/RelativityMC/VMP-fabric/blob/639c8330cde3000d0d7b7212ea2027f0b78b5af8/src/main/java/com/ishland/vmp/mixins/entitytracker/MixinEntityTrackerEntry.java

~~What brought you to this conclusion? Seems that there's about 2 blocks of error on every collision, plus the hook animates weirdly during throwing.~~

Just realised that `EntityTrackerEntry.addstartTracking(...)` -> `ServerPlayer.addPairing(...)` might know what's going on there.

Update: It's not an issue with either mixin from what I can see. Even tried overwriting VMP's behaviour entirely and there was no difference to the behaviour

There's also the extra behaviour of grappling hooks phasings through blocks if you throw them up close enough. Is it being spawned at the wrong position?

**Comment by squeeglii** [comment]
Seemingly fixed on VMP's side (0.2.0+beta.7.73+1.19.4 and above)!
