### ISSUE TITLE
CRASH java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_18798()" because "e" is null

### ISSUE THREAD

**Issue by CAYOK** [squeeglii/grapplemod-restitched#19]
## Versions:

 - The Grapple Hook Mod:  1.20.4-v1.7
 - Minecraft:  1.20.4
 - Mod Loader:  Fabric Loader v0.15.7 - Fabric API v0.96.11+1.20.4
 - MultiMC version: 0.7.0-3857

## Description:

The crash pops up whenever I'm about to use the grappling hook on any surface with the Grappling Hook Mod: Restitched. I've played many different worlds with many other mods I have, and with no other mods other than the grappling mod. I've only gotten it to crash through my modpack and it randomly crashes whenever the grapple is about to attach something. It's not consistent, it'll either crash or not but the crash is common and it's been disrupting my gameplay so many times. 

**The error is:** [Render thread/WARN]: Client disconnected with reason: Internal Exception: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_18798()" because "e" is null

Here's the log for my recent world: https://paste.ee/p/cRMvW
![image](https://github.com/squeeglii/grapplemod-restitched/assets/71987835/1bbee987-ba1d-4b5a-bd0b-a0293ddc84cb)
The image is showing what mods I installed on my multimc instance.

**Comment by squeeglii** [comment]
I've made it so that it shouldn't crash the game but the underlying issue is probably still out there. 

Open another issue if the mod starts acting funky and the logs are being spammed with warnings. For now though, I'm closing this. Should be out in v1.8 :)
