### ISSUE TITLE
[INCOMPATIBILITY] Amecs crash on changing keybind

### ISSUE THREAD

**Issue by JLUsr** [squeeglii/grapplemod-restitched#2]
**Describe the bug**
If [Amecs](https://www.curseforge.com/minecraft/mc-mods/amecs) is installed with Grapple Hook Restitched a crash will occur when changing a keybind.

**Video / Screenshots**

**Version**
Include the versions for:
 - The Grapple Hook Mod v1.4
 - The Mod Loader: Quilt 0.17.11 / Quilted Fabric API 4.0.0-beta.28+0.73.2
 - Minecraft 1.19.2
 - Amecs 1.3.8

**Output Log**
[Gist!](https://gist.github.com/JLUsr/d6c6bdaccb753f7da354f970d9df8995)

**Steps To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
1. Install Grapple Hook Mod v1.4
2. Install Amecs 1.3.8
3. Attempt to rebind a key
4. Crash

**Additional context**
(This did not occur in v1.3)

**Comment by ChromaPIE** [comment]
I don't have Amecs but Controlling in my Fabric 1.19.2 instance. It still resets my graphics and keybind settings and causes crash on rebinding keys

**Comment by JLUsr** [comment]
> I don't have Amecs but Controlling in my Fabric 1.19.2 instance.

Interestingly enough, a log for that would be very useful since I am unable to recreate this in a fresh instance of Minecraft; however, in a custom modpack I was able to duplicate the issue, but was unable to find the reason.

**Comment by squeeglii** [comment]
> I don't have Amecs but Controlling in my Fabric 1.19.2 instance.

Hopefullyyyy the settings reset is because the crash occurs somewhere roughly in the process of saving settings 😬
Send a log anyway and I'll have a look.

Found the problem with this issue though :)

**Comment by squeeglii** [comment]
Fixed as of [908e03a](https://github.com/CloudG360/grapplemod-restitched/commit/908e03a339892807f7df7caa88e9482416a18539) - Please open a new issue if Controlling is still broken in v1.5+ :)

**Comment by ChromaPIE** [comment]
> Fixed as of [908e03a](https://github.com/CloudG360/grapplemod-restitched/commit/908e03a339892807f7df7caa88e9482416a18539) - Please open a new issue if Controlling is still broken in v1.5+ :)

Is v1.5 still yet to be released? I dont see it on CurseForge nor Modrinth.

**Comment by squeeglii** [comment]
Yup - apologies there. Was trying to fix Issue #1 before I released it and got busy. Will be pushed out tonight!
