### ISSUE TITLE
disable enchantments?

### ISSUE THREAD

**Issue by R0gyman** [squeeglii/grapplemod-restitched#27]
is there a way to disable the enchantments in the config file?
if so it's not very clear on how to do so.
thanks

**Comment by squeeglii** [comment]
For the current version (v1.8), there's no way to outright disable enchantments without other mods. You can, however, make the enchantments much rarer (setting Config -> Enchantments -> [enchantment] -> Rarity in Enchantment Table to 0)

In the next version (v2) there's a built-in data pack that disables them! I'm going to close this issue as it's already implemented but v2 will be out soon-ish. I've just got to polish the rest of it.
