### ISSUE TITLE
Stutter while climbing with grappling hook

### ISSUE THREAD

**Issue by TheVillain-Inc** [squeeglii/grapplemod-restitched#30]
## Versions:

 - The Grapple Hook Mod:  `1.8`
 - Minecraft:  `1.20.1`
 - Mod Loader:  `Forge 47.3.7 with Sinytra Connector 1.0.0-beta.46`

## Description:

https://github.com/user-attachments/assets/c340ce18-c760-4882-84b8-6ea396556854

When climbing the basic Grappeling hook - a stutter or jerkiness happens. This always happenes if you 'stop/start' climbing, but sometimes happens from the beggining regardless.

To reproduce- 

Throw the hook at something directly above you with no close blocks. Climb up, stop, and then resume climbing up again. 

Throw the hook at something high above you, and then climb up against a surface.

**Comment by squeeglii** [comment]
Fixed in commit aae924345b03cb72bd7a3124a573b4e838d93d06 

It's already out for testing in v1.99 on modrinth, but that isn't a stable version.

v2.0, the stable release, should be out soonTM

**Comment by TheVillain-Inc** [comment]
Amazing!
I did notice last night that if the player 'climbs up' immediately after throwing, it sometimes animated smoothly. Weird. 


Will look out for update when it drops. Happy to do some testing if it's published anywhere. Will spiderman for science
