### ISSUE TITLE
[BUG] Wall-Slide tilt broken + Cannot stop wall-sliding.

### ISSUE THREAD

**Issue by fizzzydev** [squeeglii/grapplemod-restitched#4]
**Describe the bug**
Stuck at the wall with no camera tilt and sliding along it instead of runnning

**Video / Screenshots**

https://user-images.githubusercontent.com/116093367/232128609-476c124a-cee3-4912-9b80-53e552a00a6c.mp4

**Version**
Include the versions for:
- 1.5
- Fabric 0.14.19
- 1.19.4

**To Reproduce**
If you can, steps to reproduce the behavior, e.g.:
1. Run against a wall with Wall Running Enchantment

I was using the re:squake mod in the example video above but i could reproduce it without the mod.

**Comment by squeeglii** [comment]
Fixed as of [0d56f6d](https://github.com/CloudG360/grapplemod-restitched/commit/0d56f6d564483ae273a9a6fd030562aae958999e) (v2 branch)!

Just gotta backport it to v1.6 - in the meantime, the issue with not stopping can be fixed by bumping up the minimum wallrun speed in the config!
