### ISSUE TITLE
[INCOMPATIBILITY] cloth-config 6.3.81

### ISSUE THREAD

**Issue by BorealBlizzard** [squeeglii/grapplemod-restitched#5]
**Describe the bug**
Says grapple hook mod needs cloth config version 6.4.90 or newer but 6.3.81 is the only latest release for 1.18.2

**Video / Screenshots**
![image](https://user-images.githubusercontent.com/33204005/234753775-b65fed23-106b-4dec-a01e-2986d918fd1f.png)

**Version**
Include the versions for:
1.18.2 Fabric
Grapple Hook Mod Version 1.18.2-v1.5
Cloth Config Varsion 6.3.81

**Output Log**
https://mclo.gs/26CbZ0D

**Steps To Reproduce**
Download Fabric for 1.18.2
Download Grapple Hook mod for 1.18.2
Download cloth config for 1.18.2
error when launching

**Comment by squeeglii** [comment]
6.4.90 does exist for 1.18.2 though! -  [See here :)](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3972425)

**Comment by BorealBlizzard** [comment]
Yeah sorry, I didnt realize it was on curseforge and not modrinth
