### ISSUE TITLE
[BUG] Very high fall damage climbing with Double Jump boots

### ISSUE THREAD

**Issue by federicopirasarras** [squeeglii/grapplemod-restitched#6]
**Describe the bug**
Very high fall damage when double jumping onto some climbable surfaces, climb down it then let go of the climbable object leaving even just one single block of fall (from detatching from the climbable object to the ground or plain surface).

**Video / Screenshots**

https://github.com/CloudG360/grapplemod-restitched/assets/93835167/49378407-b85a-4232-9944-eb6d921a28f2

**Version**
Include the versions for:
- The Grapple Hook Mod v1.5
- Fabric Mod Loader - Fabric API v0.76.0
- Minecraft 1.19.3

**Output Log**

None. Crashing or performance issues never occur

**To Reproduce**

1. With Double Jump boots equipped, double jump on a climbable object (ladders, vines and probably others EXCEPT scaffholdings);
2. Climb down or let the player character descend the climbable object for a few blocks (the higher the amount of blocks climbed down the more evident the fall damage becomes);
3. Without climbing the entirety of the climbable object down to the last or base block, exit the climbable object hitbox and touch a ground surface;
4. High fall damage occurs.

**Additional context**
The more I climb down the climbable object before landing, the more the fall damage I take.
Again, it never happened with scaffholdings

Cheers!!

**Comment by squeeglii** [comment]
Fixed as of [733487d](https://github.com/CloudG360/grapplemod-restitched/commit/733487db14682b7f6f412c7374507c2707223368) (v2 branch)! -

Will be backported to v1.6 soon.

**Comment by federicopirasarras** [comment]
Thank you! Now the jungle is way way less scary haha

Man Imma have a ton of fun in that biome now jumpin round like a mad man 

a CUBE mad man! Mwahahhaahosicomf
