### ISSUE TITLE
[BUG] StackOverflow on launch w/ Diggius Maximus

### ISSUE THREAD

**Issue by squeeglii** [squeeglii/grapplemod-restitched#7]
**Version**
- The Grapple Hook Mod:  v1.5
- The Mod Loader: Fabric 0.75.3
- Minecraft: 1.19.4

**Output Log**
https://hastebin.com/share/meciviraso.wasm

**To Reproduce**
 - Installation

**Comment by unilock** [comment]
I was able to work around the bug by removing [`NonConflictingKeyBindingMixin`](https://github.com/CloudG360/grapplemod-restitched/blob/latest/src/main/java/com/yyon/grapplinghook/mixin/client/NonConflictingKeyBindingMixin.java) and installing another mod such as [NonConflictKeys](https://modrinth.com/mod/nonconflictkeys). The drawback is that conflicting keybinds will still be marked as such (with red text), but otherwise work fine.

**Comment by squeeglii** [comment]
That's useful to know actually :D 

I definitely want to keep the non-conflicting functionality built in considering how many keys clash with just the default bindings but it's just been a matter of getting around to fixing it.

Current ideas are:
 - Move it from a mixin to a class inheriting the vanilla KeyBinding and just slotting that in instead
 - Adding a counter to check for rebind loops and warning if it happens instead
 
 Haven't given either much of a look though so they could have their own pitfalls - idk

**Comment by MrEAZL** [comment]
Is there going to be a fix on this situation? I have been getting this crash since I added this mod to my mod list, I would appreciate it if this situation gets fixed

**Comment by squeeglii** [comment]
> Is there going to be a fix on this situation? I have been getting this crash since I added this mod to my mod list, I would appreciate it if this situation gets fixed

It's been on the list for a bit but it's also been a busy month 😅 - looking to start work on it soon

**Comment by squeeglii** [comment]
Closing as fixed, as of the last referenced commit (v2.0 dev branch)! ~~I'll work on porting it back to the v1.x versions over the next couple of days.~~ - nvm, did it quicker! Updated jars are uploading now.

It seems to work with Amecs too so I don't think any of the old controls-based bugs have returned. Hopefully this is a bit more compatible!
